language: go

go:
  - 1.9.x
  - 1.10.x
  - 1.11.x
  - tip

env:
  - GO111MODULE=on

install:
  - go get -v ./...
  - go build ./...
  - go get github.com/onsi/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo

script: |
  $HOME/gopath/bin/ginkgo -p -r --randomizeAllSpecs --failOnPending --randomizeSuites --race &&
  go vet &&
  [ -z "`gofmt -l -e -s -w .`" ]
